module.exports = [
    {
        name: '超级冠军--年度最佳主播',
        badges: [{
            name: '荣誉奖杯',
            icon: 'badge-ryjb'
        }, {
            name: '荣誉证书',
            icon: 'badge-ryzs'
        }, {
            name: '定制勋章（60天）',
            icon: 'badge-dzxz'
        }, {
            name: '年度最佳主播推荐标签（60天）',
            icon: 'badge-tjbq'
        }, {
            name: '定制开屏（4天）',
            icon: 'badge-dzkp'
        }, {
            name: '专属形象礼物（全站显示60天）',
            icon: 'badge-xxlw'
        }, {
            name: '2019年1、2、3月收入提成增加5%提成',
            icon: 'badge-kela'
        }, {
            name: '3000000克拉',
            icon: 'badge-tc'
        }, {
            name: '全站开播飘屏30次',
            icon: 'badge-danmu'
        }]
    }, {
        name: '单项赛冠军',
        badges: [{
            name: '荣誉奖杯',
            icon: 'badge-ryjb'
        }, {
            name: '荣誉证书',
            icon: 'badge-ryzs'
        }, {
            name: '定制勋章（30天）',
            icon: 'badge-dzxz-1'
        }, {
            name: '年度单项奖冠军推荐标签（30天）',
            icon: 'badge-tjbq'
        }, {
            name: '定制开屏（2天）',
            icon: 'badge-dzkp'
        }, {
            name: '专属形象礼物（全站显示30天）',
            icon: 'badge-xxlw'
        }, {
            name: '1000000克拉',
            icon: 'badge-tc'
        }, {
            name: '全站开播飘屏20次',
            icon: 'badge-danmu'
        }]
    }, {
        name: '单项赛亚军',
        badges: [{
            name: '荣誉奖杯',
            icon: 'badge-ryjb'
        }, {
            name: '荣誉证书',
            icon: 'badge-ryzs'
        }, {
            name: '定制勋章（20天）',
            icon: 'badge-dzxz-2'
        }, {
            name: '年度单项奖亚军推荐标签（20天）',
            icon: 'badge-tjbq'
        }, {
            name: '500000克拉',
            icon: 'badge-tc'
        }, {
            name: '全站开播飘屏10次',
            icon: 'badge-danmu'
        }]
    }, {
        name: '单项赛季军',
        badges: [{
            name: '荣誉奖杯',
            icon: 'badge-ryjb'
        }, {
            name: '荣誉证书',
            icon: 'badge-ryzs'
        }, {
            name: '定制勋章（10天）',
            icon: 'badge-dzxz-3'
        }, {
            name: '年度单项奖季军推荐标签（10天）',
            icon: 'badge-tjbq'
        }, {
            name: '300000克拉',
            icon: 'badge-tc'
        }, {
            name: '全站开播飘屏5次',
            icon: 'badge-danmu'
        }]
    }, {
        name: '至尊皇帝',
        badges: [{
            name: '至尊皇帝勋章（60天）',
            icon: 'badge-zzhdxz'
        }, {
            name: '加V标识:2018年度盛典大人物第一名：至尊皇帝(60天）',
            icon: 'badge-vtag'
        }, {
            name: '红包雨（4次/周，共96次）',
            icon: 'badge-hby',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: ['1.红包雨奖励每周用户第一次进入直播间，下发到用户背包，用户送出，全站飘屏通知抢克拉，主播不参与分成；若用户当周没有进入直播间，则当周红包雨不发放，逾期不予补发。', '2.红包雨有效期至2019年6月30日23:59:59，请及时使用。']
        }, {
            name: '上头条30个',
            icon: 'badge-stt'
        }, {
            name: '年度大人物直播间进场特效（60天）',
            icon: 'badge-jctx',
            hasInfo: true,
            infoClass: 'left',
            infoMsg: '12月5日预选赛开赛时，公布特效，敬请期待。'
        }, {
            name: '8位靓号',
            icon: 'badge-lh',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: '运营会在年度结束的7个工作日内和奖励用户确定靓号号码。用户按照大人物榜的名次，依次选择靓号。靓号选择范围：99999999/88888888/77777777/66666666/55555555/33333333。'
        }, {
            name: '大额返利（2019年1、2、3月24小时内累计充值20万及以上返利20%）',
            icon: 'badge-kela'
        }, {
            name: '上线全站飘屏（2019年1月）',
            icon: 'badge-danmu',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: '年度大人物第一名飘屏： 点击可跳转至所在直播间。若佩戴隐身卡，则上线无全站飘屏。仅每日上线首次进入直播间飘屏。'
        }]
    }, {
        name: '尊贵国王',
        badges: [{
            name: '尊贵国王勋章（30天）',
            icon: 'badge-zggwxz'
        }, {
            name: '加V标识:2018年度盛典大人物第二名：尊贵国王(30天）',
            icon: 'badge-vtag'
        }, {
            name: '红包雨（3次/周，共60次）',
            icon: 'badge-hby',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: ['1.红包雨奖励每周用户第一次进入直播间，下发到用户背包，用户送出，全站飘屏通知抢克拉，主播不参与分成；若用户当周没有进入直播间，则当周红包雨不发放，逾期不予补发。', '2.红包雨有效期至2019年6月30日23:59:59，请及时使用。']
        }, {
            name: '上头条20个',
            icon: 'badge-stt'
        }, {
            name: '年度大人物直播间进场特效（30天）',
            icon: 'badge-jctx',
            hasInfo: true,
            infoClass: 'cbottom',
            infoMsg: '12月5日预选赛开赛时，公布特效，敬请期待。'
        }, {
            name: '8位靓号',
            icon: 'badge-lh',
            hasInfo: true,
            infoClass: 'right',
            infoMsg: '运营会在年度结束的7个工作日内和奖励用户确定靓号号码。用户按照大人物榜的名次，依次选择靓号。靓号选择范围：99999999/88888888/77777777/66666666/55555555/33333333。'
        }]
    }, {
        name: '传奇亲王',
        badges: [{
            name: '传奇亲王勋章（30天）',
            icon: 'badge-cqqwxz'
        }, {
            name: '加V标识:2018年度盛典大人物第三名：传奇亲王(30天）',
            icon: 'badge-vtag'
        }, {
            name: '红包雨（3次/周，共48次）',
            icon: 'badge-hby',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: ['1.红包雨奖励每周用户第一次进入直播间，下发到用户背包，用户送出，全站飘屏通知抢克拉，主播不参与分成；若用户当周没有进入直播间，则当周红包雨不发放，逾期不予补发。', '2.红包雨有效期至2019年6月30日23:59:59，请及时使用。']
        }, {
            name: '上头条20个',
            icon: 'badge-stt'
        }, {
            name: '年度大人物直播间进场特效（30天）',
            icon: 'badge-jctx',
            hasInfo: true,
            infoClass: 'cbottom',
            infoMsg: '12月5日预选赛开赛时，公布特效，敬请期待。'
        }, {
            name: '8位靓号',
            icon: 'badge-lh',
            hasInfo: true,
            infoClass: 'right',
            infoMsg: '运营会在年度结束的7个工作日内和奖励用户确定靓号号码。用户按照大人物榜的名次，依次选择靓号。靓号选择范围：99999999/88888888/77777777/66666666/55555555/33333333。'
        }]
    }, {
        name: '高贵公爵',
        badges: [{
            name: '高贵公爵勋章（30天）',
            icon: 'badge-gggjxz'
        }, {
            name: '加V标识:2018年度盛典大人物第四名：高贵公爵(30天）',
            icon: 'badge-vtag'
        }, {
            name: '红包雨（2次/周，共24次）',
            icon: 'badge-hby',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: ['1.红包雨奖励每周用户第一次进入直播间，下发到用户背包，用户送出，全站飘屏通知抢克拉，主播不参与分成；若用户当周没有进入直播间，则当周红包雨不发放，逾期不予补发。', '2.红包雨有效期至2019年6月30日23:59:59，请及时使用。']
        }, {
            name: '上头条20个',
            icon: 'badge-stt'
        }, {
            name: '年度大人物直播间进场特效（30天）',
            icon: 'badge-jctx',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: '12月5日预选赛开赛时，公布特效，敬请期待。'
        }]
    }, {
        name: '尊荣侯爵',
        badges: [{
            name: '尊荣侯爵勋章（30天）',
            icon: 'badge-zrhjxz'
        }, {
            name: '加V标识:2018年度盛典大人物第五名：尊荣侯爵(30天）',
            icon: 'badge-vtag'
        }, {
            name: '红包雨（2次/周，共16次）',
            icon: 'badge-hby',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: ['1.红包雨奖励每周用户第一次进入直播间，下发到用户背包，用户送出，全站飘屏通知抢克拉，主播不参与分成；若用户当周没有进入直播间，则当周红包雨不发放，逾期不予补发。', '2.红包雨有效期至2019年6月30日23:59:59，请及时使用。']
        }, {
            name: '上头条20个',
            icon: 'badge-stt'
        }, {
            name: '年度大人物直播间进场特效（30天）',
            icon: 'badge-jctx',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: '12月5日预选赛开赛时，公布特效，敬请期待。'
        }]
    }, {
        name: '英勇伯爵',
        badges: [{
            name: '英勇伯爵勋章（20天）',
            icon: 'badge-yybjxz'
        }, {
            name: '加V标识:2018年度盛典大人物第六名：英勇伯爵(20天）',
            icon: 'badge-vtag'
        }, {
            name: '红包雨（1次/周，共4次）',
            icon: 'badge-hby',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: ['1.红包雨奖励每周用户第一次进入直播间，下发到用户背包，用户送出，全站飘屏通知抢克拉，主播不参与分成；若用户当周没有进入直播间，则当周红包雨不发放，逾期不予补发。', '2.红包雨有效期至2019年6月30日23:59:59，请及时使用。']
        }, {
            name: '上头条10个',
            icon: 'badge-stt'
        }, {
            name: '年度大人物直播间进场特效（20天）',
            icon: 'badge-jctx',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: '12月5日预选赛开赛时，公布特效，敬请期待。'
        }]
    }, {
        name: '显贵子爵',
        badges: [{
            name: '显贵子爵勋章（20天）',
            icon: 'badge-xgzjxz'
        }, {
            name: '加V标识:2018年度盛典大人物第七名：显贵子爵(20天）',
            icon: 'badge-vtag'
        }, {
            name: '红包雨（1次/周，共4次）',
            icon: 'badge-hby',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: ['1.红包雨奖励每周用户第一次进入直播间，下发到用户背包，用户送出，全站飘屏通知抢克拉，主播不参与分成；若用户当周没有进入直播间，则当周红包雨不发放，逾期不予补发。', '2.红包雨有效期至2019年6月30日23:59:59，请及时使用。']
        }, {
            name: '上头条10个',
            icon: 'badge-stt'
        }, {
            name: '年度大人物直播间进场特效（20天）',
            icon: 'badge-jctx',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: '12月5日预选赛开赛时，公布特效，敬请期待。'
        }]
    }, {
        name: '荣誉男爵',
        badges: [{
            name: '荣誉男爵勋章（20天）',
            icon: 'badge-rynjxz'
        }, {
            name: '加V标识:2018年度盛典大人物第八名：荣誉男爵(20天）',
            icon: 'badge-vtag'
        }, {
            name: '红包雨（1次/周，共4次）',
            icon: 'badge-hby',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: ['1.红包雨奖励每周用户第一次进入直播间，下发到用户背包，用户送出，全站飘屏通知抢克拉，主播不参与分成；若用户当周没有进入直播间，则当周红包雨不发放，逾期不予补发。', '2.红包雨有效期至2019年6月30日23:59:59，请及时使用。']
        }, {
            name: '上头条10个',
            icon: 'badge-stt'
        }, {
            name: '年度大人物直播间进场特效（20天）',
            icon: 'badge-jctx',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: '12月5日预选赛开赛时，公布特效，敬请期待。'
        }]
    }, {
        name: '华贵勋爵',
        badges: [{
            name: '华贵勋爵勋章（20天）',
            icon: 'badge-hgxjxz'
        }, {
            name: '加V标识:2018年度盛典大人物第九名：华贵勋爵(20天）',
            icon: 'badge-vtag'
        }, {
            name: '红包雨（1次/周，共4次）',
            icon: 'badge-hby',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: ['1.红包雨奖励每周用户第一次进入直播间，下发到用户背包，用户送出，全站飘屏通知抢克拉，主播不参与分成；若用户当周没有进入直播间，则当周红包雨不发放，逾期不予补发。', '2.红包雨有效期至2019年6月30日23:59:59，请及时使用。']
        }, {
            name: '上头条10个',
            icon: 'badge-stt'
        }, {
            name: '年度大人物直播间进场特效（20天）',
            icon: 'badge-jctx',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: '12月5日预选赛开赛时，公布特效，敬请期待。'
        }]
    }, {
        name: '高级爵士',
        badges: [{
            name: '高级爵士勋章（20天）',
            icon: 'badge-gjjsxz'
        }, {
            name: '加V标识:2018年度盛典大人物第十名：高级爵士(20天）',
            icon: 'badge-vtag'
        }, {
            name: '红包雨（1次/周，共4次）',
            icon: 'badge-hby',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: ['1.红包雨奖励每周用户第一次进入直播间，下发到用户背包，用户送出，全站飘屏通知抢克拉，主播不参与分成；若用户当周没有进入直播间，则当周红包雨不发放，逾期不予补发。', '2.红包雨有效期至2019年6月30日23:59:59，请及时使用。']
        }, {
            name: '上头条10个',
            icon: 'badge-stt'
        }, {
            name: '年度大人物直播间进场特效（20天）',
            icon: 'badge-jctx',
            hasInfo: true,
            infoClass: 'bottom',
            infoMsg: '12月5日预选赛开赛时，公布特效，敬请期待。'
        }]
    }
]
